<?php
if ( ! defined( 'ABSPATH' ) ) exit;

function oe_get_miejsca() {
    return array(

        // ── ŻEGLARZ JACHTOWY ──────────────────────────────────────────────
        'Żeglarz Jachtowy' => array(
            'teoria' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, ul. Traugutta 29, 80-221 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Maritime Consulting Poland, ul. Koszalińska 60, 75-900 Koszalin',
                'Dimitris Anagnastopoulis DIMITRIS FAMILY TAVERN, Poros of Troizinia, 180-20 Poros, Grecja',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRONET Sp. z o.o., ul. Wyspiańskiego 34b, 72-600 Świnoujście',
                'Dom Przyjęć Markowy, ul. Wodzisławska 23b, 43-200 Pszczyna',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'Ośrodek Szkolenia Morskiego LOK „Czarna Perła", ul. Rybacka 33, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
            'praktyka' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, PRZYSTAŃ JACHTOWA MARINA GDAŃSK, ul. Szafarnia 6, 80-775 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion 19500, Greece',
                'HERMES YACHTING, MAIN PORT LAVRION, Kountourioti, Lavrio 195 00, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'MARINA KOSZALIN, ul. Promowa, 75-900 Koszalin – Jamno',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'PRZYSTAŃ SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'PORT MORSKI JASTARNIA, ul. Portowa 26, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
        ),

        // ── JACHTOWY STERNIK MORSKI ───────────────────────────────────────
        'Jachtowy Sternik Morski' => array(
            'teoria' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, ul. Traugutta 29, 80-221 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Dimitris Anagnastopoulis DIMITRIS FAMILY TAVERN, Poros of Troizinia, 180-20 Poros, Grecja',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRONET Sp. z o.o., ul. Wyspiańskiego 34b, 72-600 Świnoujście',
                'NEXO SEJLKLUB, Sdr Hammer 23, 3730 Nexo, Dania',
                'Bornholms Regionskommune Business Center, Paradisvej 63, 3730 Nexo, Dania',
                'Restaurante La Punta Yacht Club, Puerto Deportivo S/N, 35106 Pasito Blanco, Las Palmas de Gran Canaria, Hiszpania',
                'PensionVilla Santini, Paseo Gonzalez Diaz 67, 35330 Teror Las Palmas de Gran Canaria, Hiszpania',
                'Club Marítimo Varadero de Gran Canaria S.A., Lugar Muelle Deportivo s/n, 35004 Las Palmas de Gran Canaria, Hiszpania',
                'OW Holtur - Baza Akademii Ratownictwa, ul. Koszalińska 72, 78-100 Kołobrzeg',
                'Transwaggon AB, Båthusgatan 13, 252 67 Helsingborg, Szwecja',
                'Hostel La Terrazza, Rua Franz Fanon 14, Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'C. Mencey Adeje 11, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Canary Islands International Business Centre, Av. Del Atlantico 9B, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Ośrodek Szkolenia Morskiego LOK „Czarna Perła", ul. Rybacka 33, 84-140 Jastarnia',
            ),
            'praktyka' => array(
                'GDAŃSKI OŚRODEK SPORTU, PRZYSTAŃ JACHTOWA MARINA GDAŃSK, ul. Szafarnia 6, 80-775 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Greece',
                'HERMES YACHTING, MAIN PORT LAVRION, Kountourioti, Lavrio 195 00, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'Nexø Havn Bornholm, Sdr Hammer 2D, 3730 Nexo, Dania',
                'Puerto Deportivo Pasito Blanco, Varadero, C. Goleta 2, 35106 Pasito Blanco, Las Palmas, Hiszpania',
                'Muelle Deportivo de Las Palmas, 35005 Las Palmas de Gran Canaria, Las Palmas, Hiszpania',
                'Marina Solna, ul. Warzelnicza 1, 78-100 Kołobrzeg, Polska',
                'Norra Hamnen Marina AB, Parapeten 6, 252 67 Helsingborg, Szwecja',
                'Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'Marina San Miguel Puerto Deportivo, Marina Amarilla, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'PORT MORSKI JASTARNIA, ul. Portowa 26, 84-140 Jastarnia',
            ),
        ),

        // ── STERNIK MOTOROWODNY ───────────────────────────────────────────
        'Sternik Motorowodny' => array(
            'teoria' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, ul. Traugutta 29, 80-221 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Maritime Consulting Poland, ul. Koszalińska 60, 75-900 Koszalin',
                'Maritime Consulting Poland, ul. Zwycięstwa 24a, 75-035 Koszalin',
                'Fundacja Ocean Wiedzy, ul. Wincentego Pola 12a, 41-253 Czeladź',
                'DIMITRIS FAMILY TAVERN, Poros of Troizinia, 180-20 Poros, Grecja',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRONET Sp. z o.o., ul. Wyspiańskiego 34b, 72-600 Świnoujście',
                'Dom Przyjęć Markowy, ul. Wodzisławska 23b, 43-200 Pszczyna',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Pl. Atrakcji 1, 41-501 Chorzów',
                'NEXO SEJLKLUB, Sdr Hammer 23, 3730 Nexo, Dania',
                'Bornholms Regionskommune Business Center, Paradisvej 63, 3730 Nexo, Dania',
                'Restaurante La Punta Yacht Club, Puerto Deportivo S/N, 35106 Pasito Blanco, Las Palmas de Gran Canaria, Hiszpania',
                'PensionVilla Santini, Paseo Gonzalez Diaz 67, 35330 Teror Las Palmas de Gran Canaria, Hiszpania',
                'Club Marítimo Varadero de Gran Canaria S.A., Lugar Muelle Deportivo s/n, 35004 Las Palmas de Gran Canaria, Hiszpania',
                'OW Holtur - Baza Akademii Ratownictwa, ul. Koszalińska 72, 78-100 Kołobrzeg',
                'Transwaggon AB, Bathusgatan 13, 252 67 Helsingborg, Szwecja',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Hostel La Terrazza, Rua Franz Fanon 14, Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'C. Mencey Adeje 11, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Canary Islands International Business Centre, Av. Del Atlantico 9B, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'Ośrodek Szkolenia Morskiego LOK „Czarna Perła", ul. Rybacka 33, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
            'praktyka' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, PRZYSTAŃ JACHTOWA MARINA GDAŃSK, ul. Szafarnia 6, 80-775 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Greece',
                'HERMES YACHTING, MAIN PORT LAVRION, Kountourioti, Lavrio 195 00, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'MARINA KOSZALIN, ul. Promowa, 75-900 Koszalin – Jamno',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Staw Zanzibar, Pl. Atrakcji 1, 41-501 Chorzów',
                'Nexo Havn Bornholm, Sdr Hammer 2D, 3730 Nexo, Dania',
                'Puerto Deportivo Pasito Blanco, Varadero, C. Goleta 2, 35106 Pasito Blanco, Las Palmas, Hiszpania',
                'Muelle Deportivo de Las Palmas, 35005 Las Palmas de Gran Canaria, Las Palmas, Hiszpania',
                'Marina Solna, ul. Warzelnicza 1, 78-100 Kołobrzeg, Polska',
                'Norra Hamnen Marina AB, Parapeten 6, 252 67 Helsingborg, Szwecja',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Marina Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'Marina San Miguel Puerto Deportivo, Marina Amarilla, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'PRZYSTAŃ SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'PORT MORSKI JASTARNIA, ul. Portowa 26, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
        ),

        // ── MOTOROWODNY STERNIK MORSKI ────────────────────────────────────
        'Motorowodny Sternik Morski' => array(
            'teoria' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, ul. Traugutta 29, 80-221 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Maritime Consulting Poland, ul. Koszalińska 60, 75-900 Koszalin',
                'Dimitris Anagnastopoulis DIMITRIS FAMILY TAVERN, Poros of Troizinia, 180-20 Poros, Grecja',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRONET Sp. z o.o., ul. Wyspiańskiego 34b, 72-600 Świnoujście',
                'Dom Przyjęć Markowy, ul. Wodzisławska 23b, 43-200 Pszczyna',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Pl. Atrakcji 1, 41-501 Chorzów',
                'Oficerski Yacht Club R.P. Pacific WDW, Al. Kardynała Wyszyńskiego 1, 16-300 Augustów',
                'NEXO SEJLKLUB, Sdr Hammer 23, 3730 Nexo, Dania',
                'Bornholms Regionskommune Business Center, Paradisvej 63, 3730 Nexo, Dania',
                'Restaurante La Punta Yacht Club, Puerto Deportivo S/N, 35106 Pasito Blanco, Las Palmas de Gran Canaria, Hiszpania',
                'PensionVilla Santini, Paseo Gonzalez Diaz 67, 35330 Teror Las Palmas de Gran Canaria, Hiszpania',
                'Club Marítimo Varadero de Gran Canaria S.A., Lugar Muelle Deportivo s/n, 35004 Las Palmas de Gran Canaria, Hiszpania',
                'OW Holtur - Baza Akademii Ratownictwa, ul. Koszalińska 72, 78-100 Kołobrzeg',
                'Transwaggon AB, Bathusgatan 13, 252 67 Helsingborg, Szwecja',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Hostel La Terrazza, Rua Franz Fanon 14, Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'C. Mencey Adeje 11, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Canary Islands International Business Centre, Av. Del Atlantico 9B, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'Ośrodek Szkolenia Morskiego LOK „Czarna Perła", ul. Rybacka 33, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
            'praktyka' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, PRZYSTAŃ JACHTOWA MARINA GDAŃSK, ul. Szafarnia 6, 80-775 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Greece',
                'HERMES YACHTING, MAIN PORT LAVRION, Kountourioti, Lavrio 195 00, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'MARINA KOSZALIN, ul. Promowa, 75-900 Koszalin – Jamno',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Pl. Atrakcji 1, 41-501 Chorzów',
                'Oficerski Yacht Club R.P. Pacific WDW, Al. Kardynała Wyszyńskiego 1, 16-300 Augustów',
                'Nexo Havn Bornholm, Sdr Hammer 2D, 3730 Nexo, Dania',
                'Puerto Deportivo Pasito Blanco, Varadero, C. Goleta 2, 35106 Pasito Blanco, Las Palmas, Hiszpania',
                'Muelle Deportivo de Las Palmas, 35005 Las Palmas de Gran Canaria, Las Palmas, Hiszpania',
                'Marina Solna, ul. Warzelnicza 1, 78-100 Kołobrzeg, Polska',
                'Norra Hamnen Marina AB, Parapeten 6, 252 67 Helsingborg, Szwecja',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'Marina San Miguel Puerto Deportivo, Marina Amarilla, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'PRZYSTAŃ SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'PORT MORSKI JASTARNIA, ul. Portowa 26, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
        ),

        // ── LICENCJA DO HOLOWANIA ─────────────────────────────────────────
        'Licencja do holowania narciarza wodnego lub innych obiektów' => array(
            'teoria' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, ul. Traugutta 29, 80-221 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'Maritime Consulting Poland, ul. Koszalińska 60, 75-900 Koszalin',
                'DIMITRIS FAMILY TAVERN, Poros of Troizinia, 180-20 Poros, Grecja',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'PRONET Sp. z o.o., ul. Wyspiańskiego 34b, 72-600 Świnoujście',
                'Dom Przyjęć Markowy, ul. Wodzisławska 23b, 43-200 Pszczyna',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Pl. Atrakcji 1, 41-501 Chorzów',
                'Oficerski Yacht Club R.P. Pacific WDW, Al. Kardynała Wyszyńskiego 1, 16-300 Augustów',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Hostel La Terrazza, Rua Franz Fanon 14, Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'C. Mencey Adeje 11, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Canary Islands International Business Centre, Av. Del Atlantico 9B, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'PensionVilla Santini, Paseo Gonzalez Diaz 67, 35330 Teror, Las Palmas de Gran Canaria, Hiszpania',
                'SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'Ośrodek Szkolenia Morskiego LOK „Czarna Perła", ul. Rybacka 33, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
            'praktyka' => array(
                'GDAŃSKI OŚRODEK SPORTU, ul. Żabi Kruk 15 A, 80-822 Gdańsk',
                'GDAŃSKI OŚRODEK SPORTU, PRZYSTAŃ JACHTOWA MARINA GDAŃSK, ul. Szafarnia 6, 80-775 Gdańsk',
                'MARINA KARSIBÓR, 1 Maja 5A, 72-603 Świnoujście',
                'STOWARZYSZENIE YACHT CLUB ZEFIR-DRAKKAR, Jastrząb, ul. Wojska Polskiego 71, 42-360 Poraj',
                'Champion Aktywny Wypoczynek, ul. Kormoranów 1, 42-460 Boguchwałowice',
                'Centrum Szkoleń i Fizjoterapii Joanna Szołtysek SHOW TEAM, ul. Wodna 13A, 43-200 Poręba',
                'OSiR WYSPIARZ, ul. Wybrzeże Władysława IV / ul. Jachtowa 1, 72-600 Świnoujście',
                'HERMES YACHTING, Olympic Marine S.A., Sounion rd, Lavrion, 19500, Greece',
                'HERMES YACHTING, MAIN PORT LAVRION, Kountourioti, Lavrio 195 00, Grecja',
                'HERMES YACHTING, MARINA CLEOPATRA, Aktio, Preveza, Aktio 481 00, Grecja',
                'MG Yachts Lefkas Base, Lefkas Marina, East Shore, Lefkada 311 00, Grecja',
                'LZ Yacht Club, Varna, Sea Port, Passenger\'s terminal, 9005 Varna, Bułgaria',
                'MARINA KOSZALIN, ul. Promowa, 75-900 Koszalin – Jamno',
                'Navigo Yacht Charter, Marina Dalmacija gat br. 1, 23206 Bibinje-Sukošan, Chorwacja',
                'Śląskie Wesołe Miasteczko Sp. z o.o., Pl. Atrakcji 1, 41-501 Chorzów',
                'Oficerski Yacht Club R.P. Pacific WDW, Al. Kardynała Wyszyńskiego 1, 16-300 Augustów',
                'PRZYSTAŃ PAPAJ - MARINA MIELNO, Kulczyccy Investment Sp. z o.o., ul. Bolesława Chrobrego 32, 76-032 Mielno',
                'Marina Mindelo - São Vicente - Cabo Verde, CA 1191, Republika Zielonego Przylądka',
                'Marina San Miguel Puerto Deportivo, Marina Amarilla, 38639 San Miguel, Santa Cruz de Tenerife, Hiszpania',
                'Puerto Deportivo Pasito Blanco, Varadero, C. Goleta 2, 35106 Pasito Blanco, Las Palmas, Hiszpania',
                'Muelle Deportivo de Las Palmas, 35005 Las Palmas de Gran Canaria, Las Palmas, Hiszpania',
                'PRZYSTAŃ SALEZJAŃSKI OŚRODEK MŁODZIEŻOWY – ORATORIUM DOMINIK, Czerwona Karczma 5, 14-100 Ostróda',
                'PORT MORSKI JASTARNIA, ul. Portowa 26, 84-140 Jastarnia',
                'STOWARZYSZENIE ŻEGLARZY "POGORIA IV" - KLUB ŻEGLARSKI POGORIA IV, Marianki 8 G, 41-300 Dąbrowa Górnicza',
            ),
        ),
    );
}
